### ISSUE TITLE
I can't get the extension to run

### ISSUE THREAD

**Issue by metakunt** [glacode/yamma#12]
I have installed node and the plugin, but it doesn't give me any autocomplete. However it says that it could load set.mm
How do I debug this?

**Comment by glacode** [comment]
Hi,

I'm guessing:

- with "autocomplete" you mean what I call StepDerivation (add label and hyps that "justify" the current wwf)
- with "Turning trace to verbose" you mean the Yamma setting "Diagnostic Message For Syntax Error"

If that's the case, here's what's going on:

- step derivation is available about a minute after set.mm is loaded, depending on yours machine speed (it has to parse the entire database and build an auxiliary structure; then you can work for hours, on different .mmp files, it has to be built just once; it may be some caching could speed this phase up, I should try; I was planning to show an additional information box when step derivation is available)
- Turning trace to verbose should not matter, it should just be that the above-mentioned minute was just elapsed and then autocompletion is available

If my guessing is wrong, please let me know, I will elaborate on the issue

p.s.
I use the word "autocomplete" for CompletionItems, i.e. step suggestions and syntax suggestions, that's why I'm not sure I got your point

**Comment by metakunt** [comment]
Ah that's fine. What I mean by autocomplete are 2 things. First is autocomplete in the LSP sense where you type ove and you get a list of oveq1 oveq2 oveq1i by the editor. The second is the mmj2 unify feature by pressing CTRL+U, neither was working and now it is.
