### ISSUE TITLE
Vertices must be an interval of integers starting from 0 

### ISSUE THREAD

**Issue by tirix** [glacode/yamma#6]
I often fail to generate an MMT file, with this message received from the server:
`Request failed: Request yamma/storemmt failed with message: vertices must be an interval of integers starting from 0 (-32603).`
I'm not sure when this happens, but it feels like I get it more for proofs with lots of disjunct variables constraints.

**Comment by tirix** [comment]
This is not completely blocking: when I encounter this I just do the MMT file generation manually. It's not hard but it might be a pain.

**Comment by glacode** [comment]
I've never encountered it, so far.

Can you, please, submit a "minimal" mmp that generates the error?  (so I can reproduce it locally)

What's weird, is that googling "vertices must be an interval of integers" (that I would expect to be a javascript error) returns no result

**Comment by tirix** [comment]
I could not give an example earlier as the theorems I had been working were not yet merged.
Now that it is the case, here are steps I can follow to reproduce:
- open VSCode+Yamma with set.mm commit [9a6f447](https://github.com/metamath/set.mm/commit/9a6f44705c9de1ac52af9eb774c9a9dd6c9dcb31) or later (_latest_ should do)
- open [this MMP file](https://gist.github.com/tirix/9e0d04f303b7f8a69a270f1598bfac2f) (dimkerim.mmp), which is the result of the Iast successful unification for theorem `dimkerim`
- choose "Unify + Store in MMT Folder" from the contextual menu

The error message then appears in Yamma's output:
```
Request failed: Request yamma/storemmt failed with message: vertices must be an interval of integers starting from 0 (-32603)
```
...and no MMT file is created.

This is probably not a "minimal" mmp but that's an easy one for me to produce :).

**Comment by glacode** [comment]
I've never tried Yamma with a proof as long as this one. I'm glad to see that it does not slow down too much.

There are a couple of "bugs". I'd like to read your opinion about the "best" solution. Here are the problems:


Problem/Bug 1:
the label of the first $e hyp is dimkerim.0
Yamma unification always renumbers (starting from 1) labels in the format <label>.number
This allows for clean insertion of new $e hyps (in mmj2 I always had to delete the labels manually, so that mmj2 could recreate them)
So dimkerim.0 becomes dimkerim.1
Now I see that this is a problem, when a theorem is already in the theory.
But I get a warning for this, don't you?


Problem/Bug 2:
Yamma produces a proof even if you get a warning for the first label not matching the $e hyp in the theory (this should not be the case)
And then save to .mmt tries to do its job. I've not yet debugged why a runtime error comes up, but it should not be invoked in the first place (if the theorem is "different" from the same theorem in the theory).


Possible solutions to Bug 1:
1.1 don't renumber eHyps' labels in <label>.number format, if the theorem is already in the theory
or
1.2 introduce a new $dontrenumberhyplabels statement


Possible solutions to Bug 2:
I knew I had to add a set of conditions that prevent the proof to be generated (and ehyp labels mismatch is certainly one of those cases)
Anyway, I'm curious to see why the runtime error is thrown

**Comment by tirix** [comment]
I'm working on some other long proofs and Yamma has been working quite well for them - that's great!

In Algebra it's common to name hypotheses like the things you're defining, as in `theorem.a $e |- A = ... $.`. 
I think I picked it up from theorems formalized by Mario. What I liked with this scheme is that you did not have to renumber whenever you'd reorder or insert new hypotheses. At least MMJ2 did not have that feature...
Take for example [`gsumval3`](https://us.metamath.org/mpeuni/gsumval3.html).
 
I suppose that when I first formalized `~dimkerim`, it was not yet in the theory, so I did not get that warning/error.

Next thing you could try is to remove or comment out `dimkerim` and `qusdimsum` from `set.mm` and work with that version. The issue and error messages are still there, even if there is no problem with renaming the first hypothesis.

Right now indeed when I unify Yamma is renaming my first hypothesis into `dimkerim.1` even if the theory actually has `dimkerim.0`. I can avoid that kind of naming convention if that is a problem, I don't think you need to bother especially implementing anything special for that. But in the case you would, I think 1.1 would do just fine.

**Comment by glacode** [comment]
> In Algebra it's common to name hypotheses like the things you're defining, as in `theorem.a $e |- A = ... $.`. 

I completely agree. Over the past few years, I have extensively utilized this feature to seamlessly insert new hypotheses into mmj2, avoiding any error occurrences.

Interestingly, Yamma solely renumbers labels in the format of <theoremName>.<number>, leaving labels like "theorem.a" untouched.

However, I hadn't considered a scenario where a label like "dimkerim.0" holds a significant meaning. To address this, I have written some code to implement solution 1.1, let's see how it goes.

**Comment by glacode** [comment]
> What's weird, is that googling "vertices must be an interval of integers" (that I would expect to be a javascript error) returns no result

Well, it's actually not weird at all. In fact, it's a message I intentionally included in a thrown exception... :-)

**Comment by glacode** [comment]
You were absolutely right. The issue arises when there are more than 10 variables in the $d statements since the default behavior of Array.sort() is to perform lexicographic sorting, even though the elements are numbers.

I have addressed this problem in my next commit, which should fix the sorting issue.

**Comment by tirix** [comment]
That sounds great, thanks!
Please tell me when this is released, I have some large proofs in preparation...

**Comment by glacode** [comment]
ver 0.0.7 is available, it should fix this one and improve $getproof, and semantic tokenization

**Comment by tirix** [comment]
I have (finally) completed some large proof today with a lot of distinct variables, and the MMT file generation worked like a charm!
This validates the fix, so I'm closing this issue. Thanks again!

Here is a part of resulting MMT file. I suppose this might get reorganized in the MM file when I minimize/reformat.
```
  ${
    $d A i j u $. $d A k l $. $d B j $. $d C b i j $. $d C g $. $d C w $.
    $d D i j u v $. $d D k $. $d E i j u $. $d E k l $. $d G g $.
    $d G i j u v w $. $d H i j $. $d H k l $. $d L b $. $d L j $. $d U i $.
    $d X b $. $d X g $. $d X i j u v w $. $d Y i j u v w $. $d b ph $.
    $d g i j $. $d i j ph u v w $. $d i j t $. $d j x $. $d k l ph $.
    fedgmul.a $e |- A = ( ( subringAlg ` E ) ` V ) $.
    fedgmul.b $e |- B = ( ( subringAlg ` E ) ` U ) $.
    fedgmul.c $e |- C = ( ( subringAlg ` F ) ` V ) $.
    fedgmul.f $e |- F = ( E |`s U ) $.
    fedgmul.k $e |- K = ( E |`s V ) $.
    fedgmul.1 $e |- ( ph -> E e. DivRing ) $.
    fedgmul.2 $e |- ( ph -> F e. DivRing ) $.
[.../...]
```
