### ISSUE TITLE
Add deduplication to proof compression algorithm

### ISSUE THREAD

**Issue by tirix** [glacode/yamma#7]
Following [set.mm#3185](https://github.com/metamath/set.mm/pull/3195), it seems that deduplication might not be part (or might not be optimized) in Yamma's compression algorithm.

This is not blocking since it's always possible to use metamath.exe's "save proof /compressed" to recover the same compressed proof as other tools, but it would be nice to have, to avoid spurious changes like in [set.mm#3185](https://github.com/metamath/set.mm/pull/3195).

**Comment by tirix** [comment]
I've provided an MMP file for ~fighm0to0 [here](https://gist.github.com/tirix/1c059c796896a5db6beb6e26a61a5d25).

Here is the resulting compressed proof:
```
   ( cghm co wcel wf1 w3a cfv wceq ghmid 3ad2ant1 eqeq2d wi simp2 simp3 cgrp
   ghmgrp1 grpidcl syl f1veqaeq syl12anc sylbird fveq2 sylan9eqr ex impbid ) EC
   DMNZOZABEPZGAOZQZGERZFSZGHSZVAVCVBHERZSZVDVAVEFVBURUSVEFSZUTCDEHFLKTUAUBVAUS
   UTHAOZVFVDUCURUSUTUDURUSUTUEURUSVHUTURCUFOVHCDEUGACHILUHUIUAABGHEUJUKULVAVDV
   CVDVAVBVEFGHEUMURUSVGUTCDEHFLKTUAUNUOUP $.
```
Compare with the proof generated by metamath.exe:
```
   ( cghm co wcel wf1 cfv wceq ghmid 3ad2ant1 w3a eqeq2d wi simp2 simp3 cgrp
   ghmgrp1 grpidcl syl f1veqaeq syl12anc sylbird fveq2 sylan9eqr ex impbid )
   ECDMNOZABEPZGAOZUAZGEQZFRZGHRZUTVBVAHEQZRZVCUTVDFVAUQURVDFRZUSCDEHFLKSTUB
   UTURUSHAOZVEVCUCUQURUSUDUQURUSUEUQURVGUSUQCUFOVGCDEUGACHILUHUITABGHEUJUKU
   LUTVCVBVCUTVAVDFGHEUMUQURVFUSCDEHFLKSTUNUOUP $.
```

**Comment by glacode** [comment]
ver. 0.0.8 adds the packed format (same as mmj2) for created proofs

Yamma and mmj2 produce the exact same packed format

Now, Yamma uses the packed format, in order to produce the compressed format. As a consequence:
- compressed proofs are produced in less than a second (tried for the 1500+ statements ~ fouriersw, on a really low spec virtual machine)
- deduplication should be perfect (if I hard code the same label order for a compressed proof, Yamma produces exactly the same compressed proof as mmj2)

But mmj2 seems to still be better at choosing the label order (very long proofs are about 1% shorter in mmj2)
The algorithm that mmj2 uses to order labels (in compressed proofs) is kind of weird, but I guess I will have to replicate it, in order to avoid "complaints" by cranky metamath users :-)

p.s.
ver. 0.0.8 "tolerates" errors in the underlying theory (of course those errors are displayed): this should help with changing the signature of existing theorems (this is something that I really wish mmj2 had)
This feature needs some improvements: the idea is to highlight the first mistaken theorem and those that directly depend on it, so that they can be easily updated (but I'm not there, yet)
